spring.datasource.url=jdbc:mariadb://cityEvents2-db:3306/cityEvents2_database
spring.datasource.username={cipher}121b041b757536dcdbbf6475ea256854c243bef8382eb39aeae308fd7dfa17d5
spring.datasource.password={cipher}49ba10a5c9b119c33bbc1e2db9532b7e18ab4e3d7398fc098be514bac8183d39
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.springframework=ERROR