spring.application.name=sasApp
server.port=8086

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true


application.security.jwt.secret-key={cypher}7049ab592b71ef76e287c5ded30b6e74446a140b3382121d4dc864498ea945125b5e4268478bc5ee51580e0e21ccd9488cecd77b4ec5ee59034f220fe2108a553f433fb6e5195a9e8d91e47973c40789
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework=DEBUG
